site_name: Flaxo
repo_url: https://github.com/tcibinan/flaxo/
nav:
  - Introduction: index.md
  - Deploy: deploy.md
  - Concepts: concepts.md
  - Getting started:
      - Creating an account: getting-started/creating-an-account.md
      - External services: getting-started/external-services.md
  - About: about.md
theme: material
