site_name: Flaxo
repo_url: https://github.com/tcibinan/flaxo/
nav:
  - Introduction: index.md
  - Concepts: concepts.md
  - Getting started:
    - Deploy: getting-started/deploy.md
    - Flaxo account: getting-started/account.md
    - External authorizations: getting-started/external-services.md
    - Course: getting-started/course.md
  - Contribution:
    - Build from sources: build-from-sources.md
    - Docker: docker.md
  - About: about.md
theme: material
