version: '3'
services:
  backend:
    image: flaxo/backend:${tag}
    ports:
      - 8080:8080
    volumes:
      - ${logs_dir}:/opt/flaxo/logs
    environment:
      REST_URL:
      GITHUB_ID:
      GITHUB_SECRET:
      MOSS_USER_ID:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      postgres_host: postgres
  frontend:
    image: flaxo/frontend:${tag}
    ports:
      - 80:80
  postgres:
    image: postgres:11.1
    volumes:
      - ${data_dir}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
